name: Run Cypress Tests

on:
  pull_request:
    branches: [develop]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install deps
      run: npm install

    - name: Run Cypress
      run: npx cypress run